import { Strategy } from "./types"

export const savedStrategies: Strategy[] = [
    {
        id: "1",
        name: "BBCA Momentum Pro",
        totalReturn: 24.5,
        yoyReturn: 18.2,
        momReturn: 2.1,
        weeklyReturn: 0.5,
        maxDrawdown: -8.2,
        sharpeRatio: 1.85,
        sortinoRatio: 2.12,
        calmarRatio: 2.99,
        profitFactor: 1.68,
        winRate: 68.5,
        totalTrades: 142,
        avgTradeDuration: 3.2,
        stocksHeld: 5,
        createdDate: "2024-01-15",
    },
    {
        id: "2",
        name: "Multi-Stock RSI Divergence",
        totalReturn: 18.7,
        yoyReturn: 15.3,
        momReturn: 1.8,
        weeklyReturn: 0.4,
        maxDrawdown: -12.1,
        sharpeRatio: 1.42,
        sortinoRatio: 1.78,
        calmarRatio: 1.55,
        profitFactor: 1.45,
        winRate: 61.3,
        totalTrades: 89,
        avgTradeDuration: 5.8,
        stocksHeld: 12,
        createdDate: "2024-02-03",
    },
    {
        id: "3",
        name: "Banking Sector Breakout",
        totalReturn: 31.2,
        yoyReturn: 28.7,
        momReturn: 3.4,
        weeklyReturn: 0.8,
        maxDrawdown: -15.8,
        sharpeRatio: 2.1,
        sortinoRatio: 2.45,
        calmarRatio: 1.97,
        profitFactor: 1.89,
        winRate: 72.4,
        totalTrades: 67,
        avgTradeDuration: 7.1,
        stocksHeld: 8,
        createdDate: "2024-01-28",
    },
    {
        id: "4",
        name: "TLKM Swing Trader",
        totalReturn: 15.3,
        yoyReturn: 12.8,
        momReturn: 1.2,
        weeklyReturn: 0.3,
        maxDrawdown: -6.8,
        sharpeRatio: 1.67,
        sortinoRatio: 1.89,
        calmarRatio: 2.25,
        profitFactor: 1.52,
        winRate: 64.2,
        totalTrades: 78,
        avgTradeDuration: 4.5,
        stocksHeld: 3,
        createdDate: "2024-02-10",
    },
    {
        id: "5",
        name: "Mining Stock Momentum",
        totalReturn: 42.1,
        yoyReturn: 38.9,
        momReturn: 4.7,
        weeklyReturn: 1.1,
        maxDrawdown: -18.5,
        sharpeRatio: 2.34,
        sortinoRatio: 2.78,
        calmarRatio: 2.27,
        profitFactor: 2.12,
        winRate: 69.7,
        totalTrades: 156,
        avgTradeDuration: 2.8,
        stocksHeld: 15,
        createdDate: "2024-01-05",
    },
    {
        id: "6",
        name: "Consumer Goods Scalper",
        totalReturn: 12.8,
        yoyReturn: 11.2,
        momReturn: 0.9,
        weeklyReturn: 0.2,
        maxDrawdown: -4.3,
        sharpeRatio: 1.89,
        sortinoRatio: 2.15,
        calmarRatio: 2.98,
        profitFactor: 1.73,
        winRate: 75.6,
        totalTrades: 234,
        avgTradeDuration: 1.2,
        stocksHeld: 7,
        createdDate: "2024-02-18",
    },
    {
        id: "7",
        name: "Property REIT Strategy",
        totalReturn: 8.9,
        yoyReturn: 7.8,
        momReturn: 0.6,
        weeklyReturn: 0.1,
        maxDrawdown: -3.1,
        sharpeRatio: 1.45,
        sortinoRatio: 1.67,
        calmarRatio: 2.87,
        profitFactor: 1.38,
        winRate: 71.2,
        totalTrades: 45,
        avgTradeDuration: 12.5,
        stocksHeld: 4,
        createdDate: "2024-02-25",
    },
    {
        id: "8",
        name: "Energy Sector Reversal",
        totalReturn: 35.7,
        yoyReturn: 32.1,
        momReturn: 4.2,
        weeklyReturn: 0.9,
        maxDrawdown: -22.4,
        sharpeRatio: 1.98,
        sortinoRatio: 2.34,
        calmarRatio: 1.59,
        profitFactor: 1.95,
        winRate: 58.9,
        totalTrades: 112,
        avgTradeDuration: 6.3,
        stocksHeld: 11,
        createdDate: "2024-01-12",
    },
    {
        id: "9",
        name: "Blue Chip Dividend Play",
        totalReturn: 11.4,
        yoyReturn: 10.1,
        momReturn: 0.8,
        weeklyReturn: 0.2,
        maxDrawdown: -5.7,
        sharpeRatio: 1.52,
        sortinoRatio: 1.74,
        calmarRatio: 2.0,
        profitFactor: 1.41,
        winRate: 73.8,
        totalTrades: 67,
        avgTradeDuration: 8.9,
        stocksHeld: 6,
        createdDate: "2024-02-08",
    },
]

export const popularStrategies: Strategy[] = [
    {
        id: "p1",
        name: "IDX30 Mean Reversion",
        description: "Advanced mean reversion strategy targeting IDX30 stocks with statistical arbitrage",
        creator: "ProTrader_ID",
        totalReturn: 42.8,
        yoyReturn: 39.2,
        momReturn: 4.8,
        weeklyReturn: 1.2,
        maxDrawdown: -9.5,
        sharpeRatio: 2.45,
        sortinoRatio: 2.89,
        calmarRatio: 4.5,
        profitFactor: 2.34,
        winRate: 74.2,
        totalTrades: 234,
        avgTradeDuration: 2.1,
        stocksHeld: 18,
        createdDate: "2023-11-20",
        subscribers: 1247,
    },
    {
        id: "p2",
        name: "Commodity Momentum Master",
        description: "High-frequency momentum strategy for mining and energy stocks",
        creator: "AlgoExpert88",
        totalReturn: 38.6,
        yoyReturn: 35.1,
        momReturn: 4.3,
        weeklyReturn: 1.0,
        maxDrawdown: -11.3,
        sharpeRatio: 2.12,
        sortinoRatio: 2.56,
        calmarRatio: 3.42,
        profitFactor: 2.08,
        winRate: 69.8,
        totalTrades: 189,
        avgTradeDuration: 1.8,
        stocksHeld: 22,
        createdDate: "2023-12-05",
        subscribers: 892,
    },
    {
        id: "p3",
        name: "Consumer Defensive Shield",
        description: "Low-risk strategy focusing on consumer staples with consistent returns",
        creator: "SafeInvestor",
        totalReturn: 16.4,
        yoyReturn: 14.8,
        momReturn: 1.3,
        weeklyReturn: 0.3,
        maxDrawdown: -4.2,
        sharpeRatio: 1.98,
        sortinoRatio: 2.23,
        calmarRatio: 3.9,
        profitFactor: 1.82,
        winRate: 78.5,
        totalTrades: 156,
        avgTradeDuration: 4.7,
        stocksHeld: 9,
        createdDate: "2024-01-10",
        subscribers: 654,
    },
]

export const subscribedStrategies: Strategy[] = [
    {
        id: "s1",
        name: "Tech Growth Accelerator",
        description: "Growth-focused strategy targeting technology and digital companies",
        creator: "TechGuru2024",
        totalReturn: 28.9,
        yoyReturn: 25.6,
        momReturn: 3.1,
        weeklyReturn: 0.7,
        maxDrawdown: -13.7,
        sharpeRatio: 1.76,
        sortinoRatio: 2.12,
        calmarRatio: 2.11,
        profitFactor: 1.67,
        winRate: 65.4,
        totalTrades: 98,
        avgTradeDuration: 5.2,
        stocksHeld: 14,
        createdDate: "2024-02-15",
        subscribers: 445,
        isSubscribed: true,
        subscriptionDate: "2024-03-01",
        returnSinceSubscription: 12.3,
    },
    {
        id: "s2",
        name: "Healthcare Innovator",
        description: "Innovative strategy focusing on healthcare stocks with high growth potential",
        creator: "HealthInvestor",
        totalReturn: 32.1,
        yoyReturn: 29.6,
        momReturn: 2.8,
        weeklyReturn: 0.6,
        maxDrawdown: -10.2,
        sharpeRatio: 2.05,
        sortinoRatio: 2.48,
        calmarRatio: 3.21,
        profitFactor: 1.92,
        winRate: 67.1,
        totalTrades: 110,
        avgTradeDuration: 4.3,
        stocksHeld: 13,
        createdDate: "2024-01-22",
        subscribers: 500,
        isSubscribed: true,
        subscriptionDate: "2024-03-02",
        returnSinceSubscription: 15.4,
    },
    {
        id: "s3",
        name: "Financial Services Diversifier",
        description: "Diversified strategy focusing on financial services stocks",
        creator: "FinanceGuru",
        totalReturn: 26.3,
        yoyReturn: 23.9,
        momReturn: 2.4,
        weeklyReturn: 0.5,
        maxDrawdown: -9.8,
        sharpeRatio: 1.88,
        sortinoRatio: 2.33,
        calmarRatio: 2.67,
        profitFactor: 1.75,
        winRate: 66.8,
        totalTrades: 105,
        avgTradeDuration: 4.8,
        stocksHeld: 12,
        createdDate: "2024-02-07",
        subscribers: 350,
        isSubscribed: true,
        subscriptionDate: "2024-03-03",
        returnSinceSubscription: 13.5,
    },
]
